//! Independent OS-captured oracle: no fixture here is generated by wm-theme.
use std::path::Path;
use serde::Deserialize;
use wm_theme::{DecorationStyle, FontState, RasterThemeEngine};
use wm_theme_api::{ButtonKind, ButtonRuntimeState, DecorationRequest, Point, Size, ThemeEngine};

#[path = "support/system7_fractional.rs"]
mod fractional;

#[derive(Deserialize)]
struct Case {
    file: String, depth: String, title: String, focused: bool, resizable: bool,
    pressed: Option<String>, shaded: bool, content: [u32; 4], frame_size: [u32; 2],
    parts: Vec<Part>,
}
#[derive(Deserialize)]
struct Part { file: String, offset: [u32; 2], size: [u32; 2] }

#[test]
fn every_monochrome_os_capture_matches_at_one_and_two_x() {
    let cases: Vec<Case> = serde_json::from_slice(include_bytes!("fixtures/system7/manifest.json")).unwrap();
    let engine = RasterThemeEngine::with_fonts(wm_theme::default_theme::nextstep_classic(), FontState::new())
        .with_style(DecorationStyle::System7).unwrap();
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/system7");
    let mut count = 0;
    for case in cases.into_iter().filter(|case| case.depth == "1bit") {
        for scale in [1u32, 2] {
            let request = DecorationRequest {
                content_size: Size::new(case.content[2] * scale, if case.shaded { 0 } else { case.content[3] * scale }),
                title: case.title.clone(), focused: case.focused, resizable: case.resizable,
                buttons: case.pressed.as_ref().map(|kind| ButtonRuntimeState {
                    kind: match kind.as_str() { "Close" => ButtonKind::Close, "Maximize" => ButtonKind::Maximize, _ => panic!("unknown button {kind}") },
                    hovered: true, pressed: true,
                }).into_iter().collect(),
            };
            let mut layout = engine.layout_at(&request, scale as f32);
            if case.shaded { layout.frame_size.h = layout.shaded_frame_height; }
            let visible = layout.visual_bounds();
            assert_eq!(visible.size, Size::new(case.frame_size[0] * scale, case.frame_size[1] * scale), "{}", case.file);
            let surface = engine.render_surface_at(&request, &layout, scale as f32);
            assert_eq!(surface.parts.len(), case.parts.len(), "{}", case.file);
            for (actual, expected) in surface.parts.iter().zip(&case.parts) {
                let offset = Point::new(visible.pos.x + (expected.offset[0] * scale) as i32,
                    visible.pos.y + (expected.offset[1] * scale) as i32);
                assert_eq!(actual.offset, offset, "{}", expected.file);
                assert_eq!([actual.buffer.width, actual.buffer.height], expected.size.map(|v| v * scale));
                let oracle = tiny_skia::Pixmap::load_png(fixtures.join(&expected.file)).unwrap();
                for y in 0..actual.buffer.height {
                    for x in 0..actual.buffer.width {
                        let actual_start = ((y * actual.buffer.width + x) * 4) as usize;
                        let expected_start = (((y / scale) * oracle.width() + x / scale) * 4) as usize;
                        assert_eq!(&actual.buffer.pixels[actual_start..actual_start + 4], &oracle.data()[expected_start..expected_start + 4],
                            "{} {scale}x pixel ({x},{y})", expected.file);
                    }
                }
            }
            count += 1;
        }
    }
    assert_eq!(count, 84);
}

#[test]
fn fractional_scales_match_the_documented_implementation_goldens() {
    use std::io::Read;
    let mut golden = flate2::read::ZlibDecoder::new(&include_bytes!("fixtures/system7-fractional/fractional.bin.zlib")[..]);
    let mut count = 0;
    fractional::cases(|name, bytes| {
        for actual in [name.as_bytes(), bytes.as_slice()] {
            let mut length = [0; 4];
            golden.read_exact(&mut length).unwrap();
            assert_eq!(u32::from_le_bytes(length) as usize, actual.len(), "{name}");
            let mut expected = vec![0; actual.len()];
            golden.read_exact(&mut expected).unwrap();
            if let Some(offset) = actual.iter().zip(&expected).position(|(a, b)| a != b) {
                panic!("{name}: implementation golden byte {offset} changed");
            }
        }
        count += 1;
    });
    assert_eq!(count, 144);
    assert_eq!(golden.read(&mut [0; 1]).unwrap(), 0);
}
