fps
frametime
gpu_stats
vram
font_size=28
position=top-left
log_interval=0
autostart_log=5
log_duration=90
permit_upload=0
output_folder=/home/chrisk/.local/state/chonkstep/benchmarks/hl2-i9beef-2026-09-10/mango
